apiVersion: v1
kind: Service
metadata: 
  name: first-ecr-service
spec: 
  type: NodePort
  ports: 
  - port: 8099
    targetPort: 80
    protocol: TCP
    nodePort: 30090
  selector: 
    app: first-ecr
