apiVersion: apps/v1
kind: Deployment
metadata: 
  name: first-ecr-deployment
spec: 
  selector: 
    matchLabels: 
      app: first-ecr
  replicas: 3
  template: 
    metadata: 
      labels: 
        app: first-ecr
    spec: 
      containers: 
      - name: first-ecr
        image: 667444918077.dkr.ecr.ap-northeast-1.amazonaws.com/first-ecr:1.0.1
        
